---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: /root/chef-repo/data_bags

platforms:
  - name: ubuntu/trusty64
  - name: centos-7.1

suites:
  - name: default
    run_list: tal_lamp
    attributes:
